CREATE TABLE "account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"image" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stock" (
	"material" text PRIMARY KEY NOT NULL,
	"stock_in_meters" numeric,
	"replenishment_date" date,
	"lead_time_days" integer,
	"basic_price" numeric,
	"description_2_for_the_material_group" text,
	"stock_type" text,
	"loom_type" text,
	"dyed_type" text,
	"width" numeric,
	"quality" text,
	"design" text,
	"shade_no" text,
	"fabric_type" text,
	"book_name" text,
	"book_reference_no" text,
	"ainocular_shade" text,
	"ainocular_shade_description" text,
	"ainocular_design" text,
	"ainocular_design_description" text,
	"colour_family" text,
	"colour_master" text,
	"pattern_scale" text,
	"pattern_name" text,
	"end_use" text,
	"fabric_type_description" text,
	"style" text,
	"gsm" numeric,
	"vertical_repeat" numeric,
	"horizontal_repeat" numeric,
	"repeat" text,
	"composition" text
);
--> statement-breakpoint
CREATE TABLE "invoice" (
	"id" serial PRIMARY KEY NOT NULL,
	"sales_organization" text,
	"billing_document" text,
	"item" integer,
	"invoice_date" date,
	"billing_type" text,
	"plant" text,
	"reference" text,
	"bill_doc_desc" text,
	"document_currency" text,
	"bill_to_party" text,
	"bill_to_party_code" text,
	"bill_to_party_city" text,
	"material" text,
	"basic_price" numeric,
	"billed_quantity" numeric,
	"base_unit_of_measure" text,
	"net_amount_inr" numeric,
	"discount_amount" numeric,
	"taxable_amt" numeric,
	"total_gst_amt" numeric,
	"gross_amt_fc" numeric,
	"tcs_amt" numeric,
	"gross_amount" numeric,
	"acc_net_amount_inr" numeric,
	"document_number" text,
	"fiscal_year" integer,
	"document_type" text,
	"no_of_pack" integer,
	"description_2_for_the_material_group" text,
	"cust_group_desc" text,
	"profit_center" text,
	"ship_to_party_city" text,
	"commission" numeric,
	"air_freight" numeric,
	"billing_qty_in_sku" numeric,
	"agent_code" text,
	"agent_name" text,
	"agent_state" text,
	"broker_code" text,
	"broker_name" text,
	"stock_type" text,
	"loom_type" text,
	"dyed_type" text,
	"width" numeric,
	"quality" text,
	"design" text,
	"shade_no" text,
	"fabric_type" text,
	"shade_name" text,
	"region_zone" text,
	"book_name" text,
	"book_reference_no" text,
	"ainocular_shade" text,
	"ainocular_shade_description" text,
	"ainocular_design" text,
	"ainocular_design_description" text,
	"colour_family" text,
	"colour_master" text,
	"pattern_scale" text,
	"pattern_name" text,
	"end_use" text,
	"fabric_type_des" text,
	"style" text,
	"gsm" numeric,
	"vertical_repeat" numeric,
	"horizontal_repeat" numeric,
	"composition" text
);
--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_userId_idx" ON "account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "session_userId_idx" ON "session" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "verification_identifier_idx" ON "verification" USING btree ("identifier");