CREATE TABLE "stock" (
	"material" text PRIMARY KEY NOT NULL,
	"stock_in_meters" numeric,
	"replenishment_date" date,
	"lead_time_days" integer,
	"basic_price" numeric,
	"description_2_for_the_material_group" text,
	"stock_type" text,
	"loom_type" text,
	"dyed_type" text,
	"width" numeric,
	"quality" text,
	"design" text,
	"shade_no" text,
	"fabric_type" text,
	"book_name" text,
	"book_reference_no" text,
	"ainocular_shade" text,
	"ainocular_shade_description" text,
	"ainocular_design" text,
	"ainocular_design_description" text,
	"colour_family" text,
	"colour_master" text,
	"pattern_scale" text,
	"pattern_name" text,
	"end_use" text,
	"fabric_type_description" text,
	"style" text,
	"gsm" integer,
	"vertical_repeat" numeric,
	"horizontal_repeat" numeric,
	"repeat" text,
	"composition" text
);
